name = "WaveSpec"
uuid = "908d4cf6-a6c0-449c-92e4-852c8f288332"
authors = ["Shagun Agarwal shagun.1994@gmail.com", "Thomas Kluwer", "Oriol Colomes"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
